config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :mowers do
    resources :bookings, only: [:edit, :update, :new, :create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] # est-ce correct ?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :mower
  belongs_to :user
end

app/models/mower.rb
class Mower < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :title, presence: true, length: { in: 3..140 }
  validates :price_per_day, presence: true
  validates :description, length: { maximum: 500 }
  validates :price_per_day, presence: true

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :mowers, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :user_name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 140 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :user_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def edit
    @booking = Booking.find(params[:id])
    @mower = @booking.mower
    @user = current_user
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to(user_path(@booking.user))
  end

  def new
    @mower = Mower.find(params[:mower_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @mower = Mower.find(params[:mower_id])
    @booking.mower = @mower
    @booking.user = current_user
    @booking.price = @mower.price_per_day * (@booking.return_date - @booking.pickup_date + 1)
    @booking.save ? (redirect_to user_path(@booking.user_id)) : (render :new)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to(user_path(@booking.user))
  end

  private

  def booking_params
    params.require(:booking).permit(:pickup_date, :return_date, :price)
  end
end

app/controllers/mowers_controller.rb
class MowersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @search_location = params[:query]
    nearby_users = find_nearby_users
    @mowers = find_local_mowers(nearby_users)
    @markers = markers_of_nearby_users(nearby_users)
  end

  def new
    @mower = Mower.new
    @user = current_user
  end

  def create
    @mower = Mower.new(mower_params)
    @mower.user = current_user
    @mower.save ? redirect_to(user_path(@mower.user)) : (render :new)
  end

  def edit
    @mower = Mower.find(params[:id])
    @user = current_user
  end

  def update
    @mower = Mower.find(params[:id])
    @mower.update(mower_params)

    redirect_to(user_path(@mower.user))
  end

  def show
    @mower = Mower.find(params[:id])
    @booking = Booking.new
    @user = @mower.user
    @marker = @user.geocoded? ? [{ lat: @user.latitude, lng: @user.longitude, image_url: helpers.asset_url("lawn-mower.png") }] : []
  end

  def destroy
    @mower = Mower.find(params[:id])
    @mower.destroy
    redirect_to user_path(current_user)
  end

  private

  def mower_params
    params.require(:mower).permit(:price_per_day, :title, :description, :photo)
  end

  def find_nearby_users
    if params[:query].present?
      map_center = Geocoder.search(params[:query]).first.coordinates
      nearby_users = User.near(map_center, params[:distance].to_f)  # Finds only 4 users instead of 6 even 200 km of Lausanne...
    else
      nearby_users = User.all
    end
    nearby_users
  end

  def find_local_mowers(nearby_users)
    # Unpacks all mowers of nearby users in an array (could be made more efficient)
    all_mowers = []
    nearby_users.each do |user|
      user.mowers.each do |mower|
        all_mowers << mower
      end
    end
    all_mowers
  end

  def markers_of_nearby_users(nearby_users)

    nearby_users.geocoded.select{|user| !user.mowers.empty?}.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        image_url: helpers.asset_url("lawn-mower.png"),
        info_window: render_to_string(partial: "info_window", locals: {mower: user.mowers.first})
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @all_bookings =  Booking.joins(:mower).where(mowers: {user: @user})
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to(user_path(@booking.user))
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="d-flex align-items-center justify-content-center mt-3">
  <div class="bg-white rounded p-3 shadow">
    <h3>Edit your booking !</h3>
    <h2><%= @booking.mower.title %></h2>
    <%= simple_form_for [@mower, @booking] do |f| %>
      <%= f.input :pickup_date, as: :date, html5: true %>
      <%= f.input :return_date, as: :date, html5: true %>
      <%= f.submit "Edit my booking", class: 'button' %> <%= link_to "Cancel", user_path(@user.id) %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<!--
<div class="d-flex align-items-center justify-content-center mt-3">
  <div class="bg-white rounded p-3 shadow">
    <h3>Book a mower !</h3>
    <h2><%= @mower.title %></h2>
    <%= simple_form_for [@mower, @booking] do |f| %>
      <%= f.input :pickup_date %>
      <%= f.input :return_date %>
      <%= f.submit class: 'button' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Herbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render('shared/navbar') unless controller_name == 'pages' %>
    <div style="flex:1">
      <p class="notice" style="margin:0"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'shared/footer' unless controller_name == 'pages' %>
  </body>
</html>

app/views/mowers/_header.html.erb
<div class="header">
  <div class="search-container">
    <%= render partial: 'shared/searchbar' %>
  </div>
</div>

app/views/mowers/_info_window.html.erb
<%= render layout: 'shared/mower-card', locals: {mower: mower} do %>
  <div class="title-price">
    <div>
      <h2><%= mower.title %></h2>
    </div>
    <div class="pricing-container">
      <h2 class="card-mower-pricing"><strong>$<%= mower.price_per_day.round %></strong> / day</h2>
    </div>
  </div>
  <p><%= mower.user.address %></p>
  <div class="card-mower-actions">
    <%= link_to("More info", mower_path(mower), class: "button") %>
  </div>
<% end %>

app/views/mowers/edit.html.erb
<div class="containerr">
  <div class= "form_new">
    <h1>Editing your mower</h1>
      <div>
        <%= simple_form_for @mower do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :price_per_day %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Edit my mower", class:"button" %> <%= link_to "Cancel", user_path(@user.id) %>
      <% end %>
  </div>
</div>

app/views/mowers/index.html.erb
<%= render partial: 'header' %>
<div>
  <div class="row m-0">
    <div class="col-12 col-sm-6 p-0">
        <div id="map" data-mapbox-key="<%= ENV["MAPBOX_API_KEY"] %>" data-markers="<%= @markers.to_json %>" ></div>
    </div>
    <div class="col-12 col-sm-6">
      <div class="pl-0 pt-2">
        <% if @mowers.count > 0 %>
          <div class="search-results">
            <p>Your results for: <strong><%= @search_location %></strong>.</p>
            <h3>Awesome! We found <strong><%= @mowers.count %></strong> lawn mowers available for you!</h3>
          </div>
        <% else %>
          <div class="search-results failure">
            <p>Your results for: <strong><%= @search_location %></strong>.</p>
            <h3>Oh no 😭! There are no results for that location.</h3>
          </div>
        <% end %>
        <div class="index-cards-container">
          <% @mowers.each do |mower| %>
            <%= render layout: 'shared/mower-card', locals: {mower: mower} do %>
              <div class="title-price">
                <div>
                  <h2><%= mower.title %></h2>
                </div>
                <div class="pricing-container">
                  <h2 class="card-mower-pricing"><strong>$<%= mower.price_per_day.round %></strong> / day</h2>
                </div>
              </div>
              <p><%= mower.user.address %></p>
              <div class="card-mower-actions">
                <%= link_to("More info", mower_path(mower), class: "button") %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/mowers/new.html.erb
<div class="containerr">
  <div class= "form_new">
    <h1>Creating your new mower</h1>
      <div>
        <%= simple_form_for @mower do |f| %>
        <%= f.input :title, placeholder: 'John Deer Q112' %>
        <%= f.input :description, placeholder: 'Amazing mower made with gold' %>
        <%= f.input :price_per_day, placeholder: '150$' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Create my mower", class:"button" %> <%= link_to "Cancel", user_path(@user.id) %>
      <% end %>
  </div>
</div>

app/views/mowers/show.html.erb
<div class="container mt-2">
  <div class="row mb-2 justify-content-between">
    <div class="text mr-3 col-lg-6 col-md-12">
      <h1><%= @mower.title %></h1>
        <p class="price"> CHF <%= @mower.price_per_day %> per Day</p>
      <div class="description">
        <p> <%= @mower.description %> </p>
          <p class="danger">
            <i class="fas fa-exclamation-triangle"></i>
            According to our terms and conditions, fuel tank is full when renter is taking the mower
            and so should it be returned.
          </p>
        <i class="fas fa-thumbs-up"></i> <%= rand(1..100) %>
        <i class="fas fa-thumbs-down"></i> <%= rand(0..50) %>
      </div>
      <div class="mt-3 mb-2">
        <%= link_to "Back to list", mowers_path, class: 'button' %>
      </div>
    </div>
    <div class="image_container col-lg-6 col-md-12">
      <%= cl_image_tag @mower.photo.key, class:"image shadow rounded" %>
    </div>
  </div>
  <div class="row">
    <div class="map col shadow">
      <div id="map" data-mapbox-key="<%= ENV["MAPBOX_API_KEY"] %>" data-markers="<%= @marker.to_json %>"></div>
    </div>
    <div class="col">
      <div class="bg-white rounded p-3 shadow">
        <h3>Book a mower !</h3>
        <h2><%= @mower.title %></h2>
        <%= simple_form_for [@mower, @booking] do |f| %>
          <%= f.input :pickup_date, as: :date, html5: true %>
          <%= f.input :return_date, as: :date, html5: true %>
          <%= f.submit class: 'button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1><%= image_tag('logo-white.png') %><strong>Herbnb</strong></h1>
    <p>Rent lawn mowers near your house!</p>
    <div class="search-container">
      <%= render partial: 'shared/searchbar' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="fixed-top">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">Collapsed content</h5>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<div class="banner mt-5">
  <div class="container">
    <h1><strong>Welcome to Herbnb</strong>!</h1>
    <p>Find the lawn mower that suits you!</p>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-4 ">
      <div class="card">
        <img src="https://media.gerbeaud.net/2020/02/640/tondeuse-electrique-tractee-viking.jpg" class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mower-1568302588.jpg" class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <img src="https://www.deere.com/assets/images/region-4/products/mowers/lawn-tractors/x300-series-block-r4g074029-1024x576.jpg"
         class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5">
  <div class="row">
    <div class="col-4 ">
      <div class="card">
        <img src="https://media.gerbeaud.net/2020/02/640/tondeuse-electrique-tractee-viking.jpg" class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <img src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mower-1568302588.jpg" class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <img src="https://www.deere.com/assets/images/region-4/products/mowers/lawn-tractors/x300-series-block-r4g074029-1024x576.jpg"
         class="card-img-top" alt="Great Lawn mower">
        <div class="card-body">
          <h5 class="card-title">First Lawn mower</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer mt-3">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/pages/index.html.erb
<div class="landing-container">
  <% unless user_signed_in? %>
    <p class="landing-nav">Already signed up? <%= link_to "Login", new_user_session_path, class: "nav-link" %></p>
  <% end %>
  <div class="banner-container">
    <%= render partial: 'banner' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_mower-card.html.erb
<div class="card-mower">
  <% if mower.photo.key %>
    <%= cl_image_tag(mower.photo.key) %>
  <% else %>
    <img src="https://media.gerbeaud.net/2020/02/640/tondeuse-electrique-tractee-viking.jpg" alt="Great mower">
  <% end %>
  <div class="text-container">
    <%= yield %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-brand">
    <%= image_tag('logo-white.png', style: "height: 50px;") %>
    <%= link_to("HerBnB", root_path, id: "logo-home") %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", mowers_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.user_name, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://i.pravatar.cc/50", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit my profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "New Mower", new_mower_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= form_tag(mowers_path, method: :get) do %>
  <div class="search-form-control form-group">
    <div class="search-input-container">
      <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: "Where is your house?", id: "search-input") %>
      <%= button_tag(type: "submit", class: "button") do %>
        <i class="fas fa-search"></i> Start Mowing
      <% end %>
    </div>
    <div class="max-dist-container">
      <p id="max-dist-label">Max distance</p>
      <input type="range" class="form-control-range" id="distance-range" name="distance" min="1" max="100" oninput="this.nextElementSibling.value = this.value + ' km'">
      <output>50 km</output>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="d-flex align-items-center justify-content-center mt-3">
  <div class="bg-white rounded p-3 shadow user-id">

    <h2>Edit my profile: <%= @user.user_name %></h2>

    <%= simple_form_for(@user.user_name, as: @user, url: registration_path(@user), html: { method: :put }) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :email, required: true, autofocus: true %>
        <%= f.input :address,
                    required: true,
                    input_html: { autocomplete: "address", id: "edit_address" }
                    %>
        <%= f.input :password,
                    hint: "leave it blank if you don't want to change it",
                    required: false,
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                    required: false,
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :current_password,
                    hint: "we need your current password to confirm your changes",
                    required: true,
                    input_html: { autocomplete: "current-password" } %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Update", class:"button" %>
      </div>
    <% end %>

    <h6>Unhappy? <%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></h6>

    <%= link_to "Back", :back %>
  </div>
</div>

app/views/users/show.html.erb
<div class="m-3">
  <% unless @user == current_user %>
   <h1><%=@user.user_name%></h1>
  <% end %>
  <% unless @user.mowers.empty? %>
    <div class="pl-0 pt-2">
      <h3>My mowers (<%= @user.mowers.count %>)</h3>
      <div class="index-cards-container">
        <% @user.mowers.each do |mower| %>
          <%= render layout: 'shared/mower-card', locals: {mower: mower} do %>
            <div class="title-price">
              <div>
                <h2><%= mower.title %></h2>
              </div>
              <div class="pricing-container">
                <h2 class="card-mower-pricing"><strong>$<%= mower.price_per_day.round %></strong> / day</h2>
              </div>
            </div>
            <div class="card-mower-actions">
              <%= link_to("Edit", edit_mower_path(mower), class: "button edit") %>
              <%= link_to("Delete", mower_path(mower.id), method: :delete, class: "button delete") %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% unless @user.bookings.empty? %>
    <div class="pl-0 pt-2">
      <h3>My bookings (<%= @user.bookings.count %>)</h3>
      <div class="index-cards-container">
        <% @user.bookings.each do |booking| %>
          <%= render layout: 'shared/mower-card', locals: {mower: booking.mower} do %>
            <h2><%= booking.mower.title %></h2>
            <h2 class="card-mower-pricing"><strong>$<%= booking.price.round %></strong> for <%= (booking.return_date - booking.pickup_date + 1).to_i %> days</h2>
            <p>Pickup date: <%= booking.pickup_date.strftime('%e %B %Y')%></p>
            <div class="card-mower-actions">
              <%= link_to("Edit", edit_mower_booking_path(booking.mower, booking), class: "button edit") %>
              <%= link_to("Delete", mower_booking_path(booking.mower, booking), method: :delete, class: "button delete") %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% unless @all_bookings.empty? %>
    <div class="pl-0 pt-2">
      <h3>Booking requests (<%= @all_bookings.count %>)</h3>
      <div class="index-cards-container">
        <% @all_bookings.each do |booking| %>
          <%= render layout: 'shared/mower-card', locals: {mower: booking.mower} do %>
            <h2><%= booking.mower.title %></h2>
            <h2 class="card-mower-pricing"><strong>$<%= booking.price.round %></strong> for <%= (booking.return_date - booking.pickup_date + 1).to_i %> days</h2>
            <p>Pickup date: <%= booking.pickup_date.strftime('%e %B %Y')%></p>
            <p>User: <%=booking.user.user_name%></p>
            <div class="card-mower-actions">
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>